/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.dinemore.view;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.dinemore.controller.OrderController;
import lk.ijse.dinemore.dto.OrderDTO;
import lk.ijse.dinemore.observer.Observer;

/**
 *
 * @author Nayana
 */
public class Chef extends javax.swing.JFrame implements Observer {
    private  DefaultTableModel dtm;
    /**
     * Creates new form Chef
     */
    public Chef() throws RemoteException, Exception {
        initComponents();
        dtm=(DefaultTableModel) tblChef.getModel();
        setDate();
        getLocalTime();
        loadAllOrders();
        UnicastRemoteObject.exportObject(this, 0);
        OrderController.getSubeject().registerObserver(this);
    }

    private void loadAllOrders() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tblChef.getModel();
            dtm.setRowCount(0);

            List<OrderDTO> orders = OrderController.getAllCustomers();
            if (orders == null) {
                return;
            }

            for (OrderDTO order : orders) {
                Object[] rowData = {
                    order.getReception_id(),
                    order.getDate(),
                    order.getTime(),
                    order.getCus_name(),
                    order.getTp_no(),
                    order.getQty(),
                    order.getStatus()
                };
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(Reception.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCustomerName1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQTY = new javax.swing.JTextField();
        txtOrderID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChef = new javax.swing.JTable();
        btnTakeOrder = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 90, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 51)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Time");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Customer Name");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Telephone NO");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 30));

        txtTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTel.setCaretColor(new java.awt.Color(102, 0, 0));
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        jPanel4.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 200, 30));

        txtDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDate.setCaretColor(new java.awt.Color(102, 0, 0));
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        jPanel4.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 540, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Order ID");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 30));

        txtTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTime.setCaretColor(new java.awt.Color(102, 0, 0));
        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        jPanel4.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 540, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Date");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 30));

        txtCustomerName1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCustomerName1.setCaretColor(new java.awt.Color(102, 0, 0));
        txtCustomerName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerName1ActionPerformed(evt);
            }
        });
        jPanel4.add(txtCustomerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 540, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("QTY");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 130, 30));

        txtQTY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtQTY.setCaretColor(new java.awt.Color(102, 0, 0));
        jPanel4.add(txtQTY, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 240, 30));

        txtOrderID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOrderID.setCaretColor(new java.awt.Color(102, 0, 0));
        txtOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderIDActionPerformed(evt);
            }
        });
        jPanel4.add(txtOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 170, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/dinemore/assests/feathers-lines-multi-colored-background-brush-free-stock-photos-images-hd-wallpaper.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 460));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 240));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 51)));
        jPanel2.setMinimumSize(new java.awt.Dimension(700, 100));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblChef.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Date", "Time", "Cust Name", "TP", "QTY", "Status"
            }
        ));
        tblChef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChefMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChef);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 130));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 780, 150));

        btnTakeOrder.setBackground(new java.awt.Color(0, 51, 0));
        btnTakeOrder.setText("Take Order");
        btnTakeOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTakeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTakeOrderActionPerformed(evt);
            }
        });
        jPanel3.add(btnTakeOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 100, 30));

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setText("Finsh Order");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 100, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Status");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 790, 460));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Chef  Managment");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("Dinemore");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 140, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/dinemore/assests/Logout_Rounded_Up_48px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            OrderDTO orderDTO=new OrderDTO(txtOrderID.getText(),
                    txtDate.getText(),
                    txtTime.getText(),
                    txtCustomerName1.getText(),
                    txtTel.getText(),
                    Integer.parseInt(txtQTY.getText()),
                    " Finish");
            boolean add=OrderController.updateCustomer(orderDTO);
            if (add) { 
                JOptionPane.showMessageDialog(this, "Order has been Cooking Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to Cook Order");
            }
        } catch (Exception ex) {
            Logger.getLogger(Chef.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTakeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakeOrderActionPerformed
        try {
            OrderDTO orderDTO=new OrderDTO(txtOrderID.getText(),
                    txtDate.getText(),
                    txtTime.getText(),
                    txtCustomerName1.getText(),
                    txtTel.getText(),
                    Integer.parseInt(txtQTY.getText()),
                    "cooking ");
            boolean add=OrderController.updateCustomer(orderDTO);
            if (add) { 
                JOptionPane.showMessageDialog(this, "Order has been Cooked Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to Cook Order");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Chef.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTakeOrderActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        txtQTY.requestFocus();
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIDActionPerformed
        txtDate.requestFocus();
    }//GEN-LAST:event_txtOrderIDActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        txtCustomerName1.requestFocus();
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        txtTel.requestFocus();
    }//GEN-LAST:event_txtTimeActionPerformed

    private void txtCustomerName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerName1ActionPerformed
       txtTime.requestFocus();
    }//GEN-LAST:event_txtCustomerName1ActionPerformed

    private void tblChefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChefMouseClicked
       int selectedRow=tblChef.getSelectedRow();
       String orderId=dtm.getValueAt(selectedRow, 0).toString();
        String date=dtm.getValueAt(selectedRow, 1).toString();
        String time=dtm.getValueAt(selectedRow, 2).toString();
        String cust_Name=dtm.getValueAt(selectedRow, 3).toString();
        String tp=dtm.getValueAt(selectedRow, 4).toString();
        String qty=dtm.getValueAt(selectedRow, 5).toString();
        
        txtOrderID.setText(orderId);
        txtDate.setText(date);
        txtTime.setText(time);
        txtCustomerName1.setText(cust_Name);
        txtTel.setText(tp);
        txtQTY.setText(qty);
        
    }//GEN-LAST:event_tblChefMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
         try {
            new mainpanal().setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Chef().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Chef.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTakeOrder;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChef;
    private javax.swing.JTextField txtCustomerName1;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtQTY;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObserver() throws Exception {
        loadAllOrders();
    }
    private void setDate() {
        txtDate.setText(LocalDate.now().toString());
    } 
    private void getLocalTime() {
         new Thread(new Runnable() {
             @Override
             public void run() {
                 while(true){
                     Date curDate =new Date();
                     SimpleDateFormat dateFormat=new SimpleDateFormat("HH:mm:ss aa");
                     String currenTime=dateFormat.format(curDate);
                     
                     txtTime.setText(currenTime);
                     try {
                         Thread.sleep(1000);
                     } catch (InterruptedException ex) {
                        
                     }
                 }
             }
         }).start();
    }
}
